### ISSUE TITLE
use logging module rather than print

### ISSUE THREAD

**Issue by garymcwilliams** [garymcwilliams/ggbowlscalendar#23]
replace all print statements with logging module.

set base console logger as the simplest
```
  brief:
    format: '%(message)s'
  console:
    formatter: brief
```

add to main.py (NOTE: `logging.yml` already exists

```
import logging.config
import yaml

with open('logging.yml', 'r') as f:
    log_cfg = yaml.safe_load(f.read())
    logging.config.dictConfig(log_cfg)

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
```
